[project]
name = "fparma-mods"
prefix = "fpa"
author = "FP Mod team"
modname ="fpa"
version = "1.0.0"
files = [
    "mod.cpp",
    "mod.cpp",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ca.paa",
    "README.md"
]
skip = [
    "ai_danger",
    "difficulty",
    "compositions"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]
reuse_private_key = false
