name = "fparma-mods"
prefix = "fpa"
author = "FP Mod team"
modname ="fpa"
reuse_private_key = false

[files]
include = [
    "mod.cpp",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ca.paa",
    "README.md"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]

[version]
major = 2
minor = 0
patch = 0

